name: Feature Request
description: Request for a new feature
title: "[Feature Request]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
         Before submitting your request, please review past submissions to ensure that it is not a duplicate of a known feature request.

  - type: textarea
    id: summary
    attributes:
      label: "Feature Summary"
      description: "Briefly describe the feature you’d like to see."
      placeholder: "Add support for exporting data to CSV..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Problem or Motivation"
      description: "What problem does this feature solve?"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "How would you like to see this implemented?"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "Low"
        - "Medium"
        - "High"
